export class ViewMatrizPeligros {

    id?: number;
    idplantas?: number;
    pais?: string;
    division?: string;
    planta?: string;
    area?: string;
    proceso?: string; 
    subproceso?: string; 
    actividades?: string; 
    rutinaria?: string; 
    propios?: string; 
    temporales?: string; 
    contratistas?: string; 
    total?: number; 
    peligro?: string; 
    descripcionPeligro?: string; 
    fuenteGeneradora?: string; 
    efectos?: string; 
    ingenieria?: string; 
    administrativos?: string; 
    elementospro?: string; 
    ndInicial?: string; 
    neInicial?: string; 
    npInicial?: string; 
    npInterpretacionInicial?: string; 
    ncInicial?: string; 
    nrInicial?: string; 
    cuantitativoInicial?: string; 
    cualitativoInicial?: string; 
    descripcionInicial?: string; 
    matrizrexistente?:number;
    accmayor?: string; 
    realizovaloracion?: string; 
    planAccionExistente?: string; 
    matrizeriesgo?:number;
    planAccion?: string; 
    ndResidual?: string; 
    neResidual?: string; 
    npResidual?: string; 
    npInterpretacionResidual?: string;
    ncResidual?: string; 
    nrResidual?: string; 
    cuantitativoResidual?: string;
    cualitativoResidual?: string;
    descripcionResidual?: string;
    matrizrresidual?:number;
    icr?:number;
}