import { Documento } from "../../ado/entities/documento";
import { Afp } from "../../comun/entities/afp";
import { Ccf } from "../../comun/entities/ccf";
import { Ciudad } from "../../comun/entities/ciudad";
import { Eps } from "../../comun/entities/eps";
import { Area } from "./area";
import { Cargo } from "./cargo";
import { ConfiguracionJornada } from "./configuracion-jornada";
import { HorasExtra } from "./horas-extra";
import { Usuario } from "./usuario";
import { UsuarioBasic } from './usuario-basic'

export class Empleado {
    id?: string | null;
    codigo!: string;
    direccion!: string;
    fechaIngreso!: Date;
    fechaNacimiento!: Date;
    genero!: string;
    numeroIdentificacion!: string;
    primerApellido!: string;
    primerNombre!: string;
    segundoApellido!: string;
    segundoNombre!: string;
    telefono1!: string;
    telefono2!: string;
    afp!: Afp;
    ccf!: Ccf;
    corporativePhone!: string;
    emergencyContact!: string;
    phoneEmergencyContact!: string;
    emailEmergencyContact!: string;
    ciudad!: Ciudad;
    eps!: Eps;
    tipoIdentificacion!: any;
    tipoVinculacion!: string;
    zonaResidencia!: string;
    area!: Area;
    cargo!: Cargo;
    direccionGerencia!: string;
    ciudadGerencia!: string;
    businessPartner!: Empleado;
    jefeInmediato!: Empleado;
    regional!: string;
    correoPersonal!: string;
    usuario!: Usuario;
    usuarioBasic?: UsuarioBasic;
    configuracionJornadaList!: ConfiguracionJornada[];
    horasExtraList!: HorasExtra[];
    documentosList!: Documento[];
    estado!: string;
    empresa!: string;
    nit!: string;
    enviacorreo! : boolean;
}
